### ISSUE TITLE
make install installs cound6~.pd_linux in a bogus place

### ISSUE THREAD

**Issue by umlaeute** [csound/csound_pd#3]
doing a `make install` will create `/usr/lib/csound6~.pd_linux` which is plain wrong.

the correct installation path should be something like `${prefix}/lib/pd/extra/csound6~/`.

however, since the examples aren't installed either, it's probably best to just **not install** the external in the first place.

**Comment by vlazzarini** [comment]
If you want to submit a PR to fix this, then it might be the best way forward.
