### ISSUE TITLE
question regarding monotonic versioning

### ISSUE THREAD

**Issue by umlaeute** [csound/csound_pd#4]
afaik, `csound_pd` used to be part of `Csound` and carried the same version number as the mother project.
don't users find it confusing to suddenly have to *downgrade* from `6.x` to `1.y`?

would you consider bumping the version of `csound_pd` to a number that it strictly monotonic with regard to the old external?

### background story
i'm mainly concerned about the Debian packages.
`pd-csound` used to be built from the `csound` sources, but since the external is no longer part of Csound (proper), there currently is no Debian package `pd-csound` anymore. So I'm creating a new `pd-csound` package based on *this* repository.
Debian packages allow for easy upgrading between versions; however, the package management system uses version numbers to determine which of two packages with the same name is the newer one.
While `pd-csound` was part of Csound, it used to have the same version number as Csound, so the last `pd-csound` package that was in Debian carried the version `6.10.0`.
Now *this* repository (currently) has the version `1.01.0`, which sorts before `6.10.0`, thus creating a bit of headache for people who want to do a simple system upgrade: `pd-csound` would be left at the old version :-(

there *are* possibilities to handle this (since there are a number of projects that don't always have monotonic version numbers), but if possible i'd rather avoid such quirks.

**Comment by vlazzarini** [comment]
The version was always 1.00 even when it was inside Csound. Minor changes made it go to 1.01 when we moved it out. It is not the same as the Csound version. So I am not really keen on changing this.

**Comment by umlaeute** [comment]
i see (so it was a bug in the Debian packaging in the first place).

we'll find a solution on our side then (but i thought it's better to ask :-)

**Comment by vlazzarini** [comment]
Sorry about that.

**Comment by umlaeute** [comment]
no problem.

however as a side-question: given that the version `was always 1.00`, is it "safe" to assume that the version won't move to (say) `3.14` within the next few years?

**Comment by vlazzarini** [comment]
yes, that's very safe
