### ISSUE TITLE
Possible to compile for M1 Silicon?

### ISSUE THREAD

**Issue by boonier** [csound/csound_pd#8]
just wondering if this is possible currently, I'm guessing not without some tweaks...

**Comment by rorywalsh** [comment]
If you build Csound yourself from source it's possible. But you also have to build the 3rd party libs too. Here is a barebones M1 build of Csound. https://1drv.ms/u/s!Ah4mHoWvP_Gcg6VnPPG_rYFvIiodYg?e=1rt3Pu Many of the plugin libs are missing as I had no desire to build all of their dependencies for arm64

**Comment by vlazzarini** [comment]
In fact, from the next release, the only plugin libs shipped will be the ones without dependencies, with the exception of OSC, which depends on liblo,
and portaudio/portmidi IO backends.

Plugin libs are now a separate package (which is still needing a maintainer).
========================
Prof. Victor Lazzarini
Maynooth University
Ireland

**Comment by boonier** [comment]
Thanks for the info, just seen this.

But I think Pd is complaining that the `csound6~.pd_darwin` external is the wrong architecture (makes sense), so it doesn't instantiate in the first place. I've got Csound6 install successfully.

> If you build Csound yourself from source it's possible

oh, but is `csound6~.pd_darwin` built as part of that?

**Comment by vlazzarini** [comment]
No, the csound6 pd object is not part of the Csound lib distro. It's part of this repository.

If your pd is only ARM you will need to build and install Csound under ARM, then build the csound6~ from the sources here.

Currently the releases are only x86_64 for both Csound and csound6~ because we do not have anyone who can produce releases for ARM.

**Comment by boonier** [comment]
OK gotcha. Thanks, that all makes sense.

**Comment by porres** [comment]
so, we do have Csound for apple silicon already, see https://github.com/csound/csound/issues/1685

any chance we have this for it too?

And what about we upload them all to deken?

**Comment by vlazzarini** [comment]
there is a universal build in the releases.

https://github.com/csound/csound_pd/releases
